### ISSUE TITLE
File::clean et File::write : problème de buffer

### ISSUE THREAD

**Issue by palra** [domotique-s3/dbData#25]
# Étapes à reproduire :

1. Ouvrir un fichier : `$file = new File(...);`
2. Effacer son contenu : `$file->clear();`
3. Écrire par dessus : `$file->write(...);`

Une fois ceci fait, quelques caractères blancs sont insérés avant que soit écrit le contenu demandé. Je suspecte un problème de vidange d'un quelconque cache dans la fonction `fwrite`, mais je n'en ai pas trouvé l'origine pour le moment.

**Comment by skeggib** [comment]
J'ai pu reproduire le problème, d'ailleurs l'erreur 500 que j'ai eu récement est dûe à ça.

**Comment by skeggib** [comment]
## Cause

Le problème vient du fait que lorsque le fichier est vidé de son contenu (file_put_contents), le curseur reste à sa dernière position, si cette position n'est pas égale à 0, write(...) va remplir le fichier de caractères nuls (^@ ou [NULL] en fonction de l'éditeur de texte) jusqu'au curseur.

## Solution

Placer le curseur au début du fichier après l'avoir vidé :

```php
rewind($this->handle);
```
