### ISSUE TITLE
Distinction des résultats

### ISSUE THREAD

**Issue by skeggib** [domotique-s3/dbData#26]
# Problème

Les résultats au format JSON sont très bruts, il est donc difficile de différencier les séries, les erreurs de validation et les exceptions.

# Solution proposée

Englober les résultats dans des objets.

Pour les séries :

```javascript
'data': {
    <données>
}
```

Pour une exception :

```javascript
'exception': {
    <exception>
}
```

Pour une erreur de validation :

```javascript
'validation_errors': [
    <erreurs de validation>
]
```

**Comment by armiakrajowa** [comment]
Too late?

Le jeu. 11 févr. 2016 16:40, Sebastien Klasa <notifications@github.com> a
écrit :

**Comment by palra** [comment]
On peut différencier les résultats par la valeur de retour HTTP.
Un code HTTP 200 correspond aux données, un code HTTP 400 une erreur de validation, et un code HTTP 500 une erreur.

**Comment by skeggib** [comment]
Ok, c'est déjà fait en plus non ?

**Comment by palra** [comment]
Yep, on peut close du coup ?

Le jeu. 11 févr. 2016 à 22:29, Sebastien Klasa <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Yep
