### ISSUE TITLE
Déplacer `DS3\Framework` vers son propre repository

### ISSUE THREAD

**Issue by palra** [domotique-s3/dbData#27]
On pourrait, de cette manière, maintenir à jour les classes indépendamment de dbData. Pour l'intégrer dans ce projet, on ajouterait une ligne de require en plus dans le `composer.json`.

**Comment by skeggib** [comment]
On peut require un repo git ?

**Comment by palra** [comment]
Deux possibilités : soit on l'envoie à l'index des packages de composer,
soit on peut directement require le repo

Le jeu. 11 févr. 2016 à 22:29, Sebastien Klasa <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Je pense que maintenant ça ne veille plus le coup de faire un nouveau repo ^^
