### ISSUE TITLE
Déplacer le contenu de web à la racine

### ISSUE THREAD

**Issue by palra** [domotique-s3/dbData#28]
Le dossier `web/` est censé être le seul dossier exposé au client. Or, dans `web/index.html`, il y a des liens aux scripts situés dans le dossier parent, qui lui n'est pas censé être exposé au client.
La solution à ce problème est de tout simplement virer ce dossier web. Le repository entier est censé être exposé au client, pas de risques :)

**Comment by skeggib** [comment]
Et pdo.cfg ?

**Comment by palra** [comment]
Trompé de repo :disappointed:  ... Voir celui de URLM
