### ISSUE TITLE
Commentaires de signalisation

### ISSUE THREAD

**Issue by skeggib** [domotique-s3/dbData#4]
#### Problème

Dans beaucoup de fichiers, des lignes délimitent les zones réservées aux attributs et aux méthodes de la classe décrite. Cela alourdit inutilement le code.

#### Exemple 

```php
<?php
class A {
	/* --- ATTRIBUTES --- */
	private $b;
	
	/* --- METHODS --- */
	public function getB() { return $this->b; }

}
```

#### Solution proposée

Enlever ces commentaires.

**Comment by drattak** [comment]
Je ne trouve plus de tels commentaires, ça a été résolu ?

**Comment by palra** [comment]
On va close une fois qu'on préparera la release 1.0

Le ven. 12 févr. 2016 21:42, Vincent Emile <notifications@github.com> a
écrit :
