### ISSUE TITLE
db_setup.php - readline undefined

### ISSUE THREAD

**Issue by skeggib** [domotique-s3/dbData#8]
#### Problème

Sur certaines distributions de PHP, `readline` n'est pas installé, ce qui provoque un arrêt du script dû à une erreur de fonction non définie.

#### Solution

Au choix \:
1. Demander l'installation du package `php5-readline` (pas trop bien)
2. Créer une fonction de remplacement, si la fonction n'est pas définie, voir [cette proposition](http://stackoverflow.com/a/25340777)

**Comment by skeggib** [comment]
Comme on utilise la console de Symfony on peut fermer ?

**Comment by drattak** [comment]
Ça me paraît logique.

Le ven. 12 févr. 2016 07:15, Sebastien Klasa <notifications@github.com> a
écrit :

**Comment by armiakrajowa** [comment]
Ouais mais il existe une alternative a readline

**Comment by skeggib** [comment]
On n'utilise plus readline

Le ven. 12 févr. 2016 11:12, armiakrajowa <notifications@github.com> a
écrit :
